# Netlify settings
#
# Other Netlify files:
# - runtime.txt: version of Python to build with
# - yarn.lock: indicates we need lock isntalled
#
# “base” is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!
# “command” is your build command,
# “publish” is the directory to publish (relative to root of your repo),
#

[build]
  base    = ""
  publish = "docs/.vuepress/dist"
  command = 'export GIT_SHA=$COMMIT_REF && pip install -e ".[dev]" && yarn docs:build'

# redirect from /guide/core_concepts to /core/concepts
[[redirects]]
  from = "/guide/core_concepts/*"
  to = "/core/concepts/:splat"

[[redirects]]
  from = "/cloud/first-steps.html"
  to = "/cloud/"
#
# redirect from /cloud/cloud_concepts to /cloud/concepts
[[redirects]]
  from = "/cloud/cloud_concepts/*"
  to = "/cloud/concepts/:splat"

# redirect from /guide to /core
[[redirects]]
  from = "/guide/*"
  to = "/core/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
